# Generated by Django 4.1.5 on 2023-01-04 21:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleados_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='Ninguna'),
            preserve_default=False,
        ),
    ]
