# Generated by Django 4.1.5 on 2023-01-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleados_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='full_name',
            field=models.CharField(blank=True, max_length=101, verbose_name='Nombre completo'),
        ),
    ]
